### ISSUE TITLE
Dashboard menu broken

### ISSUE THREAD

**Issue by sangnguyenplus** [skillcraft-io/sc-referral#4]
It's overriding the admin panel menu.

<img width="451" alt="image" src="https://github.com/skillcraft-io/sc-referral/assets/6972407/c7edb1d0-f23b-47cc-b72f-38cd24ca016f">

**Comment by skillcraft-io** [comment]
@sangnguyenplus - What changed in the way registering menu items that would cause this? As of  7.1.4, there was no issue

**Comment by sangnguyenplus** [comment]
@skillcraft-io

Actually, this is our CMS issue.

Please merge this PR https://github.com/skillcraft-io/sc-referral/pull/5

The same as we did for plugin Member.
<img width="808" alt="image" src="https://github.com/skillcraft-io/sc-referral/assets/6972407/1dd75801-f934-455d-bb73-9e8c7f4fa886">

We will find a better way for dashboard menu to prevent conflicts.
