### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Lazarus132** [skillcraft-io/sc-referral#6]
Can you please explain how I can adjust this? I have not been able to find a setting anywhere.

**Comment by skillcraft-io** [comment]
@Lazarus132 -
This plugin currently just works, very little needs to be adjusted, and if it does, its likely on the code level. Happy to advise, but I do need some more information about what your looking to adjust.

**Comment by Lazarus132** [comment]
I can't even find any setting in the admin panel to create afiliate links for example

**Comment by Lazarus132** [comment]
Probably can't use it at all at the moment, via the admin panel, in PHP coding, unfortunately I am an absolute layman and have very little knowledge of it.

**Comment by skillcraft-io** [comment]
> I can't even find any setting in the admin panel to create affiliate links for example

Referral links are automatically generated for the models that are registered with the plugin. IE, we provide native support for the member plugin... SO when the member logins, the visit the referral page, there is a referral link above the table. 
<img width="1886" alt="referral_table" src="https://github.com/skillcraft-io/sc-referral/assets/41481716/64c5218a-16f2-4b2c-b2e7-e9a2a4f2f94c">


> Probably can't use it at all at the moment, via the admin panel, in PHP coding, unfortunately I am an absolute layman and have very little knowledge of it.

If your not using the member plugin and would like to use it, you would need to know PHP, above what's provided in the readme.

**Comment by Lazarus132** [comment]
Ok good to know, I'll have to try that out.

**Comment by Lazarus132** [comment]
How do I register via the plugin, after the customer registration, do I only find the Customer & Vendor Dashboard?

**Comment by Lazarus132** [comment]
Currently this plugin causes a problem in the customer edit page:

Call to a member function getKey() on string {"view":{"view":"/mnt/web611/b1/05/532599505/htdocs/platform/core/base/resources/views/forms/form-tabs.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-1929782197 data-indent-pad=\" \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#3682</a><samp data-depth=1 class=sf-dump-expanded>

**Comment by skillcraft-io** [comment]
@Lazarus132 - Please open an issue regarding this - thanks
