### ISSUE TITLE
Plugin leads to an error in the user processing of the admin panel

### ISSUE THREAD

**Issue by Lazarus132** [skillcraft-io/sc-referral#7]
Currently this plugin causes a problem in the customer edit page:

Call to a member function getKey() on string {"view":{"view":"/mnt/web611/b1/05/532599505/htdocs/platform/core/base/resources/views/forms/form-tabs.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-496143971 data-indent-pad=\" \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#3682</a><samp data-depth=1 class=sf-dump-expanded>

**Comment by skillcraft-io** [comment]
@Lazarus132 - Please either screenshot the error you see on screen and include the tracestack, or just post some of the tracestack.  

Also, When you refer to customers, are you talking of the ecommerce plugin?

**Comment by Lazarus132** [comment]
Great thanks, it works now, but the loading times are extremely long
