### ISSUE TITLE
Customers Register to Referral

### ISSUE THREAD

**Issue by Lazarus132** [skillcraft-io/sc-referral#9]
But how can you add or register a customer now?

**Comment by skillcraft-io** [comment]
I am not sure what you mean add or register a customer now? 

After registering the Customer Model with the plugin, When a custom is registered or added to your system, a referral alias will be created.

**Comment by Lazarus132** [comment]
So I registered again as a customer with a different e-mail for test purposes while the plugin is activated, and there was no entry.

**Comment by Lazarus132** [comment]
Where should this entry be? I couldn't find anything either on the Admin page or in the Customer Dashboard. And in the Settings -> REFERRALS, there was nothing to be seen.

**Comment by skillcraft-io** [comment]
You should see the alias on the table for customers and on the edit page

<img width="1726" alt="alias_ss" src="https://github.com/skillcraft-io/sc-referral/assets/41481716/857d5879-be6f-43cf-aafb-5b6c88dc9b37">

**Comment by Lazarus132** [comment]
Sorry, but I can't see anything there.
![Screenshot (101)](https://github.com/skillcraft-io/sc-referral/assets/78088157/79f64a90-0bc4-479c-be4e-80fbb7432523)

**Comment by Lazarus132** [comment]
So it looks like it's not quite finished yet.

**Comment by Lazarus132** [comment]
You seem to be testing that in the localhost, that might be the problem, I've had other plugins that ran in the localhost and not on a domain.

**Comment by Lazarus132** [comment]
Strange, I also have it in the localhost without success.

**Comment by skillcraft-io** [comment]
I use all my plugins in a production environment.. Though I build membership and other non-ecommerce type sites,  and actually do not use the ecommerce at the moment.

You would need to register the customer as per the readme

```php
if (defined('REFERRAL_MODULE_SCREEN_NAME')) {
    ReferralHookManager::registerHooks(Customer::class, 'Customer');
    ReferralHookManager::registerFormHooks(CustomerCreateFormRequest::class, 'Customer Add');
    ReferralHookManager::registerFormHooks(CustomerEditFormRequest::class, 'Customer Edit');
}
```

As support for Customers/Ecommerce is not built in, after registering the class, there would be no customer area (where customer login) table of referrals/referral link. This would need to be added in.  Without your customers would not be able to know the referral link for their account.

I probably would not recommend this plugin for you, if your not comfortable/knowledgeable with writing code.

**Comment by Lazarus132** [comment]
Ok, maybe add that soon?

**Comment by Lazarus132** [comment]
That's not a lot of code, can't you tell me in which file and where it has to be inserted?

**Comment by Lazarus132** [comment]
Your name says it all, you really need skill in dealing with your plug-ins. No offense meant.

**Comment by Lazarus132** [comment]
The readme file does not say where to adjust or enter this.

**Comment by Lazarus132** [comment]
I only know a bit about js, html & css, I haven't really done anything with PHP so far.

**Comment by skillcraft-io** [comment]
The code can be placed inside of the Boot of the ecommerce service providers or really any service provider...

I do not have plans to add official support for ecommerce atm. Does not mean it wont happen, but right now I have no eta and or anything. The package is available and of course, maybe another developer wants to add it in.

My plugins are geared for Developers, who can dive into code, and add and enhance functionality into projects they are managing. They are not specifically for the non-developer looking for a ready made complete solution.

Though this referral plugin does deliver a complete referral system... then what? Generally most systems that offer referrals, give a reward, but this can be anything and a developer still needs to execute the action they desire once one has a referral.

Could be anything, developers choice.

**Comment by Lazarus132** [comment]
Oh well, I thought that this is an affiliate program so that the admin can always see how many users have clicked on this link and then send a reward to their users.

**Comment by Lazarus132** [comment]
That you can then simply set an amount in the settings, e.g. 10,000 clicks = 500$

**Comment by skillcraft-io** [comment]
> Oh well, I thought that this is an affiliate program so that the admin can always see how many users have clicked on this link and then send a reward to their users.

ahh ic - that's not the intent of this plugin, but I do have a plugin that does something like that. Actually its a series of plugins that basically when all installed gives you a complete affiliate network. 

Would you manually be sending users their rewards?
The affiliate links.. do they link to product links, or external/custom links?

**Comment by Lazarus132** [comment]
If there is no other way, I thought that it would be possible to set a variable amount in the settings and that the amount would be automatically transferred to the other customer's account based on the purchases of other people via this link via PayPal, for example.

e.g. K registers on my site, advertises for me on Youtube and enters the link, another person makes a purchase via it and in the settings I have activated e.g. 1purchase from link 1 = 5$ So the plugin automatically sends the amount to K via the specified PayPal ID after a successful order.

**Comment by Lazarus132** [comment]
For example, to support Youtubers and they support me.

**Comment by skillcraft-io** [comment]
Yes, that could be possible and would be a neat little plugin.

**Comment by Lazarus132** [comment]
Would you consider developing something like this? And a thank you to all the developers who develop all these great plugins for free, I just wish that they would be adapted as soon as a new version is released.

**Comment by skillcraft-io** [comment]
It might be something I consider, id have to think about the plugin a bit more and its total usage possiblities

**Comment by Lazarus132** [comment]
Ok, then I'll wait with bated breath for your decision.
